<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__xtSCL</name>
   <tag></tag>
   <elementGuidId>94b0f4c4-e847-4e19-9597-5b11f349971b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.xtSCL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e9883621-d3ba-4dbb-a1e7-067371ebf2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xtSCL</value>
      <webElementGuid>c7b5e96e-6ff8-42c4-b12e-f30e446d40f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;L3eUgb&quot;]/div[@class=&quot;o3j99 ikrT4e om7nvf&quot;]/form[1]/div[1]/div[@class=&quot;A8SBwf emcav&quot;]/div[@class=&quot;UUbT9&quot;]/div[@class=&quot;aajZCb&quot;]/div[@class=&quot;xtSCL&quot;]</value>
      <webElementGuid>0f7291ea-48a4-42d4-85ad-fe1fa0ecaf54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>1f8894eb-13e7-4c61-82cd-3c341e2946a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
