<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bliss bibliographic classification</name>
   <tag></tag>
   <elementGuidId>ff74da6a-2894-43ff-b9c4-ce35ab33d513</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/div[4]/div[7]/ul/li[2]/ul/li[2]/ul/li[2]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4fe6845e-01fe-437a-a2eb-b68d44133d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Bliss_bibliographic_classification#_Classifications_(BC2)</value>
      <webElementGuid>0b032988-a9d1-4268-bd22-18afd497b590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bliss bibliographic classification</value>
      <webElementGuid>ecdcaa99-3e33-4c7f-a5c2-ad78131d4095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-parser-output&quot;]/div[@class=&quot;contentsPage contentsPage--topic&quot;]/div[@class=&quot;contentsPage__section&quot;]/ul[1]/li[2]/ul[1]/li[2]/ul[1]/li[2]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>281fb9f8-cc95-421e-975d-751e31a367f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/div[4]/div[7]/ul/li[2]/ul/li[2]/ul/li[2]/ul/li/a</value>
      <webElementGuid>247662d8-d349-4768-b5a7-b98b2493222a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bliss bibliographic classification')]</value>
      <webElementGuid>aa655c7b-e271-4d40-a1e0-4af896a3577d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Joint Academic Classification of Subjects'])[1]/following::a[1]</value>
      <webElementGuid>81ef505c-9974-4d76-ac1a-23d58927aac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Colon classification'])[1]/preceding::a[1]</value>
      <webElementGuid>dca88f3d-2264-493a-93bf-e486300d4d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cutter Expansive Classification'])[1]/preceding::a[2]</value>
      <webElementGuid>ef7d3673-3480-45ba-bf52-a9be7b03d95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bliss bibliographic classification']/parent::*</value>
      <webElementGuid>0984e20e-dc25-4351-97e0-4c56427af1cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wiki/Bliss_bibliographic_classification#_Classifications_(BC2)')]</value>
      <webElementGuid>d7c06bf5-fda1-4980-9cf6-7bf39083e415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>208439df-aa9b-4fbe-a4c5-5d715f08a0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Bliss_bibliographic_classification#_Classifications_(BC2)' and (text() = 'Bliss bibliographic classification' or . = 'Bliss bibliographic classification')]</value>
      <webElementGuid>fcc922aa-8d89-47e0-a3e6-23a49bc660b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
